kafka-producer:
  bootstrap.servers: localhost:9092
  topic: test-topic
  client.id: kafka-producer-client
  linger.ms: 10
  acks: all
kafka-consumer:
  bootstrap.servers: localhost:9092
  topic: test-topic
  group.id: kafka-consumer-group
  auto.offset.reset: earliest
  enable.auto.commit: false
